np.empty((row,cols), dtype)

In [2]:
import numpy as np
np.empty((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

np.ones((row,cols), dtype)

In [3]:
x = np.ones(6) #here in the args 6 means 6 cols and in output we get 6 columns
x

array([1., 1., 1., 1., 1., 1.])

In [4]:
y = np.ones((3,5),)
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
z = np.ones((3,5),dtype = int)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
# now 
# np.zeros((row,cols),dtype)
# work same as ones, instead of one in array it display 0

In [7]:
q = np.ones((6,6), dtype = str)
q

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [8]:
w = np.ones((6,6), dtype = bool)
w

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [9]:
# same goes for zeros in str it willl return empty and for bool it retrun false

np.arange(start, end, step)

In [10]:
a = np.arange(1,20) # here step is deafult = 1
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
s = np.arange(1, 20, 2)
s
# we can use this while giving axis to matplot

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
d = s.reshape((2,5))
d

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [17]:
f = np.arange(1, 100, 2)
f

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [18]:
g = f.reshape((10,5))
g

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [20]:
h = g.flatten()
h

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [21]:
j = g.ravel()
j

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

a.ravel():
(i) Return only reference/view of original array
(ii) If you modify the array you would notice that the value of original array also changes.
(iii) Ravel is faster than flatten() as it does not occupy any memory.
(iv) Ravel is a library-level function.

a.flatten() :
(i) Return copy of original array
(ii) If you modify any value of this array value of original array is not affected.
(iii) Flatten() is comparatively slower than ravel() as it occupies memory.
(iv) Flatten is a method of an ndarray object.

#### Array slicing

In [26]:
a = np.arange(1,51)
a = a.reshape((10, 5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [27]:
# now access array value usinh index

In [28]:
a[1]

array([ 6,  7,  8,  9, 10])

In [30]:
a[1,4]

10

In [31]:
a[2:5]#this will return row from index 2 to 4.

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
a[:, 2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [34]:
a[2:5, 4]

array([15, 20, 25])

In [35]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])