##### need to work on some point 
#### 1. after importing dataset identify and remove column which is not usefull. some column are (landmarks,desc)
#### 2. drop all duplicates rows from dataset
#### 3. 

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [62]:
df = pd.read_csv('../datasets/mumbai.csv')
df.head(10)

price                                            Address    area  \
0  22400000.0        Chembur, Mumbai - Harbour Line, Maharashtra   629.0   
1  35000000.0        Chembur, Mumbai - Harbour Line, Maharashtra   974.0   
2  31700000.0  Ghatkopar East, Mumbai - Central Line, Maharas...   968.0   
3  18700000.0  Plot Number 283, Road Number 3, Jawahar Nagar,...   629.0   
4  13500000.0  malad east, Malad East, Mumbai - North Mumbai,...  1090.0   
5  13000000.0  Bhandup, Mumbai, Bhandup, Mumbai - Central Lin...   630.0   
6  20700000.0  Siddharth Nagar, Goregaon West, Mumbai, Gorega...  1188.0   
7  22900000.0  Goregaon West, Mumbai, Best Nagar - Goregaon W...   968.0   
8  17000000.0  Wadala East, Mumbai, Wadala, Mumbai - Harbour ...   820.0   
9  81000000.0  Worli, Mumbai, Worli, Mumbai - South Mumbai, M...  3260.0   

    latitude  longitude  Bedrooms  Bathrooms  Balcony              Status  \
0  19.032800  72.896357       2.0        2.0      NaN  Under Construction   
1  19.032800  72.896357       3.0        2.0      NaN  Under Construction   
2  19.085600  72.909277       3.0        3.0      NaN  Under Construction   
3  19.155756  72.846862       2.0        2.0      2.0       Ready to Move   
4  19.177555  72.849887       2.0        2.0      NaN                 NaN   
5  19.148058  72.937725       2.0        2.0      NaN                 NaN   
6  19.154919  72.843566       2.0        2.0      2.0                 NaN   
7  19.147269  72.848351       3.0        3.0      NaN                 NaN   
8  19.015128  72.858064       2.0        2.0      NaN                 NaN   
9  19.001640  72.826532       3.0        3.0      3.0       Ready to Move   

       neworold  parking Furnished_status  Lift  \
0  New Property      NaN              NaN   2.0   
1  New Property      NaN              NaN   2.0   
2  New Property      1.0              NaN   2.0   
3  New Property      1.0              NaN   3.0   
4  New Property      1.0      Unfurnished   2.0   
5  New Property      1.0      Unfurnished   2.0   
6  New Property      1.0   Semi-Furnished   5.0   
7  New Property      1.0      Unfurnished   6.0   
8  New Property      1.0      Unfurnished   3.0   
9        Resale      3.0              NaN   4.0   

                                          Landmarks type_of_building  \
0                                               NaN             Flat   
1                                               NaN             Flat   
2                                               NaN             Flat   
3                                    Laxmi Callista             Flat   
4                            near uper govind nagar             Flat   
5  LBS road bhandup west 7 min walking from station             Flat   
6                                     goregaon west             Flat   
7     Near Ram Mandir railway station goregaon west             Flat   
8                                      Dosti acres.             Flat   
9                                    prime property             Flat   

                                                desc    Price_sqft  
0  \n\n\n                                Right fr...  35612.082671  
1  \n\n\n                                Right fr...  35934.291581  
2  \n                    \n                    \n...  32747.933884  
3  \n\n\n                                Welcome ...  29729.729730  
4  \n                    \n                    \n...  12385.321101  
5  \n\n\n                                Located ...  20634.920635  
6  \n\n\n                                Ekta tri...  17424.242424  
7  \n                    \n                    \n...  23657.024793  
8  \n\n\n                                PreLaunc...  20731.707317  
9  \n                    \n                    \n...  24846.625767

In [63]:
df.shape

(6255, 17)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6255 entries, 0 to 6254
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   price             6255 non-null   float64
 1   Address           6255 non-null   object 
 2   area              6255 non-null   float64
 3   latitude          6255 non-null   float64
 4   longitude         6255 non-null   float64
 5   Bedrooms          6255 non-null   float64
 6   Bathrooms         6255 non-null   float64
 7   Balcony           2376 non-null   float64
 8   Status            5774 non-null   object 
 9   neworold          6255 non-null   object 
 10  parking           2129 non-null   float64
 11  Furnished_status  3600 non-null   object 
 12  Lift              1678 non-null   float64
 13  Landmarks         2617 non-null   object 
 14  type_of_building  6255 non-null   object 
 15  desc              6255 non-null   object 
 16  Price_sqft        6255 non-null   float64


In [65]:
df.isnull().sum()

price                  0
Address                0
area                   0
latitude               0
longitude              0
Bedrooms               0
Bathrooms              0
Balcony             3879
Status               481
neworold               0
parking             4126
Furnished_status    2655
Lift                4577
Landmarks           3638
type_of_building       0
desc                   0
Price_sqft             0
dtype: int64

In [66]:
#working for coulmn balcony 
df.Balcony.unique()
#now here in balcony many rows are nan, show replaing it with 0

array([nan,  2.,  3.,  1.,  4.,  5.,  6.,  7.,  8.])

In [67]:
df['Balcony'] = df['Balcony'].fillna(0)
df.Balcony.unique()

array([0., 2., 3., 1., 4., 5., 6., 7., 8.])

In [68]:
df.isnull().sum()

price                  0
Address                0
area                   0
latitude               0
longitude              0
Bedrooms               0
Bathrooms              0
Balcony                0
Status               481
neworold               0
parking             4126
Furnished_status    2655
Lift                4577
Landmarks           3638
type_of_building       0
desc                   0
Price_sqft             0
dtype: int64

In [69]:
# column status
df['Status'].unique()

array(['Under Construction', 'Ready to Move', nan], dtype=object)

In [70]:
Statusnan = df[df['Status'].isna()]
Statusnan.shape

(481, 17)

##### here for column status to replace nan value, for  that idea is
##### 1. check column "neworold" if this column has resale than status column nan values should be replaced with 'Ready to Move' string

In [71]:
Statusnan

price                                            Address    area  \
4     13500000.0  malad east, Malad East, Mumbai - North Mumbai,...  1090.0   
5     13000000.0  Bhandup, Mumbai, Bhandup, Mumbai - Central Lin...   630.0   
6     20700000.0  Siddharth Nagar, Goregaon West, Mumbai, Gorega...  1188.0   
7     22900000.0  Goregaon West, Mumbai, Best Nagar - Goregaon W...   968.0   
8     17000000.0  Wadala East, Mumbai, Wadala, Mumbai - Harbour ...   820.0   
...          ...                                                ...     ...   
6158   4500000.0     Kala Ghoda, Mumbai - South Mumbai, Maharashtra   900.0   
6209  22500000.0         Colaba, Mumbai - South Mumbai, Maharashtra   800.0   
6213   6000000.0  Vasai west, Vasai West, Mumbai - Mira Road and...   600.0   
6228  16500000.0  Lower Parel East, Mumbai - South Mumbai, Mahar...   700.0   
6249  11500000.0  bldg no-137, axiom aven, near ganesh mandir, p...   550.0   

       latitude  longitude  Bedrooms  Bathrooms  Balcony Status      neworold  \
4     19.177555  72.849887       2.0        2.0      0.0    NaN  New Property   
5     19.148058  72.937725       2.0        2.0      0.0    NaN  New Property   
6     19.154919  72.843566       2.0        2.0      2.0    NaN  New Property   
7     19.147269  72.848351       3.0        3.0      0.0    NaN  New Property   
8     19.015128  72.858064       2.0        2.0      0.0    NaN  New Property   
...         ...        ...       ...        ...      ...    ...           ...   
6158  18.929830  72.834210       3.0        2.0      2.0    NaN        Resale   
6209  18.903700  72.813143       2.0        2.0      2.0    NaN  New Property   
6213  19.369335  72.806127       4.0        3.0      2.0    NaN        Resale   
6228  18.992092  72.829684       2.0        2.0      0.0    NaN        Resale   
6249  19.079069  72.907974       2.0        2.0      0.0    NaN  New Property   

      parking Furnished_status  Lift  \
4         1.0      Unfurnished   2.0   
5         1.0      Unfurnished   2.0   
6         1.0   Semi-Furnished   5.0   
7         1.0      Unfurnished   6.0   
8         1.0      Unfurnished   3.0   
...       ...              ...   ...   
6158      NaN              NaN   NaN   
6209      1.0   Semi-Furnished   NaN   
6213      NaN      Unfurnished   NaN   
6228      NaN        Furnished   NaN   
6249      NaN      Unfurnished   NaN   

                                             Landmarks  type_of_building  \
4                               near uper govind nagar              Flat   
5     LBS road bhandup west 7 min walking from station              Flat   
6                                        goregaon west              Flat   
7        Near Ram Mandir railway station goregaon west              Flat   
8                                         Dosti acres.              Flat   
...                                                ...               ...   
6158                                               NaN              Flat   
6209                  JCBN international School 1.2 km              Flat   
6213                                               NaN  Individual House   
6228                                               NaN              Flat   
6249                    pant nagar, near ganesh mandir              Flat   

                                                   desc    Price_sqft  
4     \n                    \n                    \n...  12385.321101  
5     \n\n\n                                Located ...  20634.920635  
6     \n\n\n                                Ekta tri...  17424.242424  
7     \n                    \n                    \n...  23657.024793  
8     \n\n\n                                PreLaunc...  20731.707317  
...                                                 ...           ...  
6158  \n                    \n                    \n...   5000.000000  
6209  \n\n\n                                KEM Hosp...  28125.000000  
6213                                           

##### replacing nan value with neworold column based on resale string

In [72]:
StatusWNeworold = df[(df['Status'].isna()) & (df['neworold'] == 'Resale')]
StatusWNeworold.shape

(255, 17)

In [73]:
def handle_status_forresale(value):
    if value in StatusWNeworold:
        print(value)
#         return 'others'
    else:
        print(value)
#         return value
       
    
    
df['Status'] = df['Status'].apply(handle_status_forresale)
df['Status'].value_counts()

Under Construction
Under Construction
Under Construction
Ready to Move
nan
nan
nan
nan
nan
Ready to Move
nan
nan
Ready to Move
nan
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
nan
nan
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
nan
nan
nan
Ready to Move
nan
nan
Ready to Move
nan
nan
nan
nan
nan
nan
nan
nan
Ready to Move
nan
Ready to Move
Ready to Move
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
Ready to Move
nan
nan
Ready to Move
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
Ready to Move
nan
nan
nan
nan
nan
nan
Ready to Move

Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to

Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move


Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
nan
nan
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Read

Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to

Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
nan
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
nan
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move
Ready to Move


Series([], Name: Status, dtype: int64)

In [52]:
df[(df['Status'].isna()) & (df['neworold'] == 'Resale')]


C:\Users\Ajay\AppData\Local\Temp\ipykernel_1012\2018262509.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[(df['Status'].isna()) & (df['neworold'] == 'Resale')].fillna('Ready to Move', inplace=True)


In [53]:
df.isnull().sum()

price                  0
Address                0
area                   0
latitude               0
longitude              0
Bedrooms               0
Bathrooms              0
Balcony                0
Status               481
neworold               0
parking                0
Furnished_status       0
Lift                   0
Landmarks           3638
type_of_building       0
desc                   0
Price_sqft             0
dtype: int64

In [ ]:
df[df['Status'].isna()].shape

In [21]:
df.isnull().sum()

price                  0
Address                0
area                   0
latitude               0
longitude              0
Bedrooms               0
Bathrooms              0
Balcony                0
Status               481
neworold               0
parking             4126
Furnished_status    2655
Lift                4577
Landmarks           3638
type_of_building       0
desc                   0
Price_sqft             0
dtype: int64

#### clening parking column

In [22]:
df['parking'].unique()

array([ nan,   1.,   3.,   2.,  11.,   4.,  20.,  30.,   5.,   8., 603.,
       205., 401.,  75.,   7., 185., 150.,  10.,   6., 202.,  14.,  12.,
        55., 163., 104., 702.,   9.,  21.,  40., 105., 101., 418.,  60.,
       125.,  65.,  18.,  15., 601.,  22.,  24.,  26., 801., 102., 302.,
        16.])

##### in this coulumn we have large no. of rows having nan values. Instead of droping  rows. Replacing nan value with 0

In [23]:
df['parking'] = df['parking'].fillna(0)
df['parking'].unique()

array([  0.,   1.,   3.,   2.,  11.,   4.,  20.,  30.,   5.,   8., 603.,
       205., 401.,  75.,   7., 185., 150.,  10.,   6., 202.,  14.,  12.,
        55., 163., 104., 702.,   9.,  21.,  40., 105., 101., 418.,  60.,
       125.,  65.,  18.,  15., 601.,  22.,  24.,  26., 801., 102., 302.,
        16.])

In [24]:
df.isnull().sum()

price                  0
Address                0
area                   0
latitude               0
longitude              0
Bedrooms               0
Bathrooms              0
Balcony                0
Status               481
neworold               0
parking                0
Furnished_status    2655
Lift                4577
Landmarks           3638
type_of_building       0
desc                   0
Price_sqft             0
dtype: int64

##### Check Furnished_status   

In [26]:
df['Furnished_status'].unique()

array([nan, 'Unfurnished', 'Semi-Furnished', 'Furnished'], dtype=object)

##### so, what here we can do is try to replace nan with 'Unfurnished' string and later check its outcome and acording to that we can 
##### if needed change nan value with some other string

In [29]:
df['Furnished_status'] =df['Furnished_status'].fillna('Unfurnished')

In [30]:
df.isnull().sum()

price                  0
Address                0
area                   0
latitude               0
longitude              0
Bedrooms               0
Bathrooms              0
Balcony                0
Status               481
neworold               0
parking                0
Furnished_status       0
Lift                4577
Landmarks           3638
type_of_building       0
desc                   0
Price_sqft             0
dtype: int64

##### column lift

In [32]:
df['Lift'].unique()

array([ 2.,  3.,  5.,  6.,  4., nan,  8.,  1.,  7.,  0., 10.,  9.])

In [33]:
df['Lift'].value_counts()

2.0     758
1.0     327
3.0     220
4.0     174
0.0      55
5.0      51
6.0      49
7.0      18
8.0      11
10.0     11
9.0       4
Name: Lift, dtype: int64

In [35]:
df['Lift'] =df['Lift'].fillna(0.0)

In [36]:
df.isnull().sum()

price                  0
Address                0
area                   0
latitude               0
longitude              0
Bedrooms               0
Bathrooms              0
Balcony                0
Status               481
neworold               0
parking                0
Furnished_status       0
Lift                   0
Landmarks           3638
type_of_building       0
desc                   0
Price_sqft             0
dtype: int64

##### landmarks column

In [40]:
df['Landmarks'].unique()

array([nan, 'Laxmi Callista', 'near uper govind nagar', ...,
       'Jyoti stationery is below the building, you can visit site to enquire',
       'pant nagar, near ganesh mandir',
       'Lokhandwala Complex, Andheri West'], dtype=object)